name: flutter_getui
description: getui plugin for flutter, only Android and IOS are supported
version: 1.0.0
homepage: https://github.com/Wayaer/flutter_getui.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: flutter.getui
        pluginClass: GeTuiPlugin
      ios:
        pluginClass: GeTuiPlugin
