name: flutter_getui
description: getui plugin for flutter, only Android and IOS are supported
version: 0.0.2
homepage: https://github.com/Wayaer/flutter_getui.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: flutter.getui
        pluginClass: GeTuiPlugin
      ios:
        pluginClass: GeTuiPlugin
